name: Continuous integration
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "30 15 * * 5"
env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.67.1

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt,clippy

      - uses: Swatinem/rust-cache@v2

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo clippy --examples -- -D warnings

      - name: Build
        run: cargo build --all-targets

      - name: Doc
        run: cargo doc --no-deps

      - name: Tests
        run: cargo test --all
